version: "3.7"

services:
    db:
        image: postgres
        container_name: desafio_supertest
        restart: always
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=fin_api
        volumes:
            - pgdata:/data/postgres
volumes:
    pgdata:
        driver: local
    

